### ISSUE TITLE
Floating text - Double size, quad size, vertical

### ISSUE THREAD

**Issue by NicolasUmiastowski** [jncraton/box-line-text#10]
I was not able to make it work with arrows.... I am certainly missing something.

**Comment by jncraton** [comment]
I'll be the first to admit the the UX for these features is clunky.

When you create a box or a line, the cursor that is placed on the screen is not the exactly the same as the one you get when clicking an arbitrary location. The text typed there is actually a child of the box or line. This allows the container to grow as needed when the text content grows.

An unfortunate artifact of this is that using the arrow keys or PgUp/PgDown to adjust styles will only impact the outer container. There is not a way to adjust the styles of the text attached to a line or box.

A possible workaround is:

1. Create a line
2. Create text somewhere else with the style you want
3. Move it into position over the line

At some point in the future, I'd like to add a few more features to this application. I honestly didn't envision text styles being very useful initially, but I wanted them included in the data format so that I could eventually make it easy to add large emojis to diagrams to create things like [this](https://box-line-text.netlify.app/#;210%F0%9F%92%BB;a423;a453;a483;213%F0%9F%93%B1;206%F0%9F%96%A5;c7148;083%C2%A0+Web$Server;051;ab53;ce432Database).

**Comment by NicolasUmiastowski** [comment]
No it's ok it works quite well actually when you just position the cursor in a free space and use the arrow.

**Comment by NicolasUmiastowski** [comment]
very useful app.
I used it this morning to make a live introduction to story mapping.

and also use it for live mind mapping.

**Comment by jncraton** [comment]
Great! I'm glad that it is working well for you.
