### ISSUE TITLE
Persist data

### ISSUE THREAD

**Issue by Shuunen** [jncraton/box-line-text#4]
Hi ! Great project, I love minimal app like this ❤️ 

It would be great to store the diagram status : 
- in url : to let users send diagram via copy pasting url 
- in localstorage : to avoid losing the diagram by closing the tab or browser accidently (or system crash, cat on keyboard, nuclear attack, ...)

I'm wondering now about the size limit in url address & the way of encoding boxes, lines and text all together in a string.

For the local storage, it should be easier without this string restriction.

**Comment by jncraton** [comment]
Thanks for the feedback. I'm glad that you've enjoyed this project. 😀

I've played around with adding persistence via the URL fragment in a feature [branch](https://github.com/jncraton/box-line-text/tree/persistence). You can play around with it here:

https://persistence--box-line-text.netlify.app

Here's an example URL with stored data:

https://persistence--box-line-text.netlify.app/#PHNlY3Rpb24gc3R5bGU9IndpZHRoOiAzMThweDsgaGVpZ2h0OiAxOTBweDsgbGVmdDogNjJweDsgdG9wOiA2MnB4OyI+PHAgY29udGVudGVkaXRhYmxlPSJ0cnVlIj5TdGF0ZSBpcyBzYXZlZCBpbiB0aGUgVVJMIGZyYWdtZW50PGJyPjwvcD48L3NlY3Rpb24+

**Comment by Shuunen** [comment]
Wow nice !

I just looked at url length limitation, everyone agrees on keeping them under 2000 characters to have a good compatibility everywhere.

Your sample has a length of 244.

I tried to create a big BLT of random but in the end it was not persisted in url, I pushed it too far 😛 

![image](https://user-images.githubusercontent.com/439158/81160339-3b37e880-8f8a-11ea-85b0-75795a907f10.png)

[blt-random-art.zip](https://github.com/jncraton/box-line-text/files/4585811/blt-random-art.zip)

this is the url I have [right now](https://persistence--box-line-text.netlify.app/#PHNlY3Rpb24gc3R5bGU9IndpZHRoOiAzMThweDsgaGVpZ2h0OiAxOTBweDsgbGVmdDogNjJweDsgdG9wOiA2MnB4OyI+PHAgY29udGVudGVkaXRhYmxlPSJ0cnVlIj5TdGF0ZSBpcyBzYXZlZCBpbiB0aGUgVVJMIGZyYWdtZW50PGJyPjwvcD48L3NlY3Rpb24+PHNlY3Rpb24gc3R5bGU9IndpZHRoOiA2MnB4OyBoZWlnaHQ6IDI1NHB4OyBsZWZ0OiAxOTBweDsgdG9wOiAyNTRweDsiPjxwIGNvbnRlbnRlZGl0YWJsZT0idHJ1ZSIgc3BlbGxjaGVjaz0iZmFsc2UiIGRhdGEtZ3JhbW09ImZhbHNlIj48L3A+PC9zZWN0aW9uPg==) but it's just the beginning of my test

![image](https://user-images.githubusercontent.com/439158/81160568-818d4780-8f8a-11ea-9182-8bf5d83114e4.png)

**Comment by jncraton** [comment]
Haha. Cool.

One challenge with just serializing the DOM like I'm doing currently is that any elements added by extensions or userscripts are also stored, so the storage requirements can get very large quickly.

I've pushed a change that uses LZ compression for the URI data. That should also help a lot with the size.

Here's your[ example art cleaned up a bit](https://persistence--box-line-text.netlify.app/#DwZwpgxgLglg9gOwAQigTwDZgLwCIDuMAJlABYBcSAzAIwAcADgB4DcSpYMA5qVJTQE4ADMzZYAZnyQA2AEyikUOA0pzRuAHzAGSCIihgEBojCgBDAEZY8UAE4BXMJoDK5g0hggUZgG5giHshkYEgAqgBKADJI4rZmXAC2hlDAFrZaAPQMmeDQ8AhaubCIKOjWBMRkqvKs7Jw8UrIArAAsChJSgiK1SipIzW2smtooDGAYGBAcEADWeOJmGOC4SERm5gC0XHEJCfOLy7r6yf6mluV2jpobN7c3wFk5kMUFoM-5pZg4FSQUSDSyaTtMCSfiAhS9ShNGjdFjDHSoL42ZSUDbSIFDUbjSbTOa4BZLJyrdZmLY7Pb4g5EvRGE4mcxWb6XJyZbIPIr5QrvEqI8qEX5gjFiEGdYQQlFIaGw+GfC4StFClYgMYTKaQPEEw5rTbbMy7faElY0gy0+nnJkOFkPNkZDmILl5Hllb78qr-cG1DjcXiC4Gg91CxQS6RURhDLQIlU49UGrUksl6ima6nHU1nRk2S2aADqpHWADIEBZlSxrVoTD4NJ5FBwHhWI6yno7XnbkLyXZU-gDAx1KANxX0AOxCGpwiOypny9HqLGq3Gxona0m6-WUw1HWlphkXLON9nclsHid4V1dj1sL0NX21XvUOijoN9ENhscjZXYtWzBcrJcJ1fJo1U2MdMdyuDQMBgBJTCQOBxDLYB61IewEjMBA6xgSttD3W0DwdF5j1wS8fQDP0pBaFpA0hJBB2ncM3yjT8NSpH94xXJNmI3E1gO3C0wPgnDmzwj52xPTtrwvepiLUG8RUoUMHyougBEGV9Iw-ec1zjHVyW-Ti6RA3iWRmGAEACAB+fjWyEp0kR+N1pOFf1aBfR8oRhdRxxE3AqIVGd3znGNNMXVidKCwDN2481Mz4x590Et5mwI09xKQW9uwHNzpU851kT6XzMX86MvzC4ltMTXTjX0njoqtWKBJebLbNvfseglKU-IYjSANK5dQu6yqtyi7zdwAK3sVBVjifAkDMFBuGQAA9Bb4NbJKxJImSnPvDLJXcuiERy7yp0VWciqY9dfzYiqgNOarhpim0rIS-CvKIqRnNIqFBxU1yNtU07GN0y6+o4gbIoze7ase3DnuEw63rk+hPpkUMdvS-aAa6jjgfKkqwduobmWGOqntW17JPepHNqkYcFIldH-sKwGSpx-9QZus0IaJ7DSaPLzkv6Vpkfa1q+i6Dy30OnzaLhTHAu61n2PXfHOdAqGmwa2GbL5daWscqQRbYKi9ZlLzpZOpmsYukLcf6jmDJq4nofisnDoFvXUtk3bYV+j6MbN46OvU+XsZttnlftu7ucsmHXds92hepzKdvkiWDts82g4C4qFbDpXDhVh3IadjXOUlpqvaab6U6p2XLZD62yvDgvI8J3cAA14PT8pb2fHaTblnPQ6b-OUwigmud3AB5LuCNvWn+8TuvOobrTett9nx9VwzNBn2Lu++W8q5+qjxYKleh8b9fm7HriJ7VzRO-3ufK+r0W+yXpUL-Ote-1H8K77b0dhoPebID54HnjLX65ELbfyBnna6W8i7cwgKhJAYA-DIAYBgMwaAVp8zdutVOnoKbVGRjRSiEoKFp0Hj-YKI9EGAOQbuGOLsCHxyIdtEh3opAOU9v6ah78kB0CoFleiwdL6-yunjVuk8Hql3tFrNshCBR3gfAjGQD5IGUL6EpFSps4EswQTIpBUcWEk1juwnWqjiESR4WQpO1EoFUQEE0F8BiJF0JYgwkxTCzHyLiprOO1i3SGzqPYzR5CRw7QXv7QxucfF21MW3MCaQwBmCIKwoJViOyqLCRovh89olCJhLIUcHjs5eJ6n-RhVUUksjSRkrJZdwG4FvCIn2Li3FZzOvAxJm8-H1M0IWYsDA2AjJLEgCZYyplFkmdM8ZcyZkLM9lAKA9gIBgFnl5dpoidp6J6czBJ19-56UGnIlkSR1jbMOreVxLlFJ7PPp4vpJzannIfhoNUYBwA3Irv6DpMSZZfxeUY-pEdkkXM0CAMwGytmxWCbkt0tj+E02cVQ4pjMpaB2eZU15NTfF1KhTzGGrTdmdODKjXFvSwVvMJR8neGhwAwqSCgMA-gQD4MSvzdasS7FXn+EIOgPYvY0CoC0OmT5ymeXicPOlSTBnEuaYoxFolVFn35cRD2aUmgCAeRKE2MrQXHIJQqolnzlWHm5So5FtdwkCsKaKpo4q0ZijicauVpqBnmsZZa6yyiOGqL4Rov2+t+AtGHDtQ2FSaUmukWahlwC-VKLWkG9RpDImOJoBGilQ5gVGrxbSr1ELFUWosWw61gbbUuQ0dqp1LqhHRoLbGz18bvWJuLiSitL0bV-GDRm0NqL+B0CXr9Jt4jC1xpBiWn1Sby3ZMrSErsbrNW8K0aKwc55fqCMZrKq+xaW6QrLc7BdPaq19vTREx1-oaCbp0ZQHdMajmtunYe0tvr50tJfje3V+q+ihpBZOl9G8Z0du5isjIKyAA6KzYNLJYJB+DSAoN-J7qK9EkrKAwMOVbKRr7b6zs7QAfRIxkLlZ6l38BXUO-4v7XViNaZnalz791ttA+DY9CjXhktFS0IQ96kD3Jw6veh8r20ccZXB0ZizpOzNk1J+ZSGFMzIALIwSQMgMwym2AACEkDRAACqocPl7WQNA9pGwlAB2h+K2NvsI9zMaE0YXTTIOsFAHB2BmC8AgOAXmUjPx2aZ29J82oWcAy21j+GAEOd3AkNASALBNIRTktV1bkYHKEYa8uco8rAps0WuzBGwO7m03JxT8mlNVcqzVirdXlnVfqzJksUGYONYa7VjrTXytdd681vrPX+tDcG4NjIZHP2KJ4zejDaNZCDncQVqdIH7MlbAgwcapAPBQCDDWEIEEoJQBAAs0ADA0FeSS7MbYcB7CmQ2HoDAcBbCUFsFwCwAAKWQEaAA0-Rvu-cHAASjYPdx7z3XtvekEIH7kPodCCBzEfQGwFhQQwGgSg+YACO9g4BQBYGYWwMBFhIBuzAPQRAQgJCO1jnHLAfuY+x7jyIGziCzWcKhLwoQECk7gOT+nNOfswoQCADY4ACfiDYOIRHIAYAAC8wCqBaAAOgeWAJgUANiLHmpQTZtJbBjkAFZk7JTuvEC7c0VerMPunm8JyRomD3FYk0m5UZ3Dog6e0gF7730TQ+kD7+HkujBI71DAVH6Pqe4-x4TjAxOudk4p1ThntOpnh5YEziALOkBs6F2EWPPOwB89xwL9nIuwBi4l1L2X8v+h0GVxCVX6vNdcAQNrk4evEtmEu7Ya7t23dg-e80JoP2B9D6aE0IHmhAA8G4ATv2jeoT3FNxoQgKKzet8x3DduisxdWyyQgZB0EJDgCNasUG4DjbAd+qQGxLcAmzTbqpit3mO87WYGXr+3-v4-5-r-3+f+-7---gA--dlYAkA0AsA8AiAyAqA6AmA2wOA+AhAxApAhAtZVAtA9AjA9ANAbAnA3AvA-Aggwgog4gkg0g7AssAAKByxM39Cvx2joMxELn8XViAA).

Ultimately, a proper serializer and deserializer will probably be necessary to make this work efficiently.

**Comment by Shuunen** [comment]
> any elements added by extensions or userscripts are also stored

damn, indeed my grammar skills have been exposed ^^

> I've pushed a change that uses LZ compression for the URI data. That should also help a lot with the size. Here's your example art cleaned up a bit.

cool ! why not use the [npm pkg](https://www.npmjs.com/package/lz-string) ?

> Ultimately, a proper serializer and deserializer will probably be necessary to make this work efficiently.

is this not enough for a first version ?

**Comment by jncraton** [comment]
> why not use the npm pkg ?

I'm not currently dependent on Node, so adding the entire Node ecosystem when I only need one JS file seemed a little excessive. I did use the JS file from that project.

> is this not enough for a first version ?

I'm not comfortable with this currently. Here are a some of my concerns:

1. If this feature is made generally available, I need to make sure that URLs keep working in perpetuity. That makes future changes to the application more difficult.
2. I'm not comfortable with the current privacy implications with regard to data created by the user agent being shared with others in a way that is not expected. This could currently reveal private data stored in the DOM by extensions.
3. The current implementation is a textbook XSS attack. That shouldn't matter much for the Netlify version, but this could create very real security implications for anyone who decides to self-host this on their own domain.

In terms of functionality, though, this does seem to get the job done.

**Comment by Shuunen** [comment]
> adding the entire Node ecosystem when I only need one JS file seemed a little excessive

I agree, npm independent projects are quite rare these days, and surely faster to use (clone & start)

> I need to make sure that URLs keep working in perpetuity

Do you mean no-breaking changes ? Because it's commonly accepted when projects jump from a major version to another major according to SEMVER

> I'm not comfortable with the current privacy implications with regard to data created by the user agent being shared with others in a way that is not expected

Maybe a share floating button could display a modal and link with a note below explaining risks of sharing this url
![image](https://user-images.githubusercontent.com/439158/81205996-b968af00-8fcb-11ea-8c10-3516f77fb57b.png)
(just used as a quick mocking tool, nice ^^)

> The current implementation is a textbook XSS attack

Right, maybe not taking the DOM as input would solve this, so this get back to serialization

**Comment by jncraton** [comment]
> Do you mean no-breaking changes ? Because it's commonly accepted when projects jump from a major version to another major according to SEMVER

Not necessarily. I just want to minimize breakage as much as possible. I'd want to have versioned URLs between major versions so that users can still access their old data. If I'm storing the entire DOM as data, even a seemingly minor change could require a major version change, creating more work for everyone.

I've pushed a change to serialize the elements more intelligently. This uses less space for most documents than before, obviates the need for a compression step, and should take care of the XSS issue.

Here's your [example](https://persistence--box-line-text.netlify.app/#W1sxLDEsNSwzLCJTdGF0ZSBpcyBzYXZlZCBpbiB0aGUgVVJMIGZyYWdtZW50Il0sWzMsNCwxLDQsIi0tLS0tLS0tIl0sWzIsOCwyLDAsIiJdLFszLDgsMiwwLCIiXSxbMiwxMCwyLDIsIldoYXQlQzIlQTBpcyB0aGUiXSxbNCwxMSwyLDAsIiJdLFs2LDEwLDIsMiwibGltaXQgb2ZodW1hbiJdLFs3LDEyLDAsMiwiIl0sWzYsMTQsMiwxLCJraW5kID8iXSxbNSw4LDEsMCwiIl0sWzIsOCwyLDAsIiJdLFs0LDgsMCwwLCJqdXN0IGRyYXcgYSBzaWduIF5eIl0sWzYsOCwyLDAsIiJdLFs5LDIsMCw1LCIiXSxbMTAsMiwwLDUsIiJdLFsxMSwyLDAsNSwiIl0sWzgsMyw0LDAsIiJdLFs4LDQsNCwwLCIiXSxbOCw1LDQsMCwiIl0sWzgsNiw0LDAsIiJdLFs5LDUsMCwwLCJYIl0sWzEwLDQsMCwwLCJPIl0sWzExLDQsMCwwLCJPIl0sWzksMywwLDAsIlgiXSxbOSw0LDAsMCwiTyJdLFsxMiw3LDAsMCwiY2FuIGV2ZW4gcGxheSJdLFsxMiwxMiw2LDEsIiJdLFsxMiwxMyw2LDEsIiJdLFsxMiwxNCw2LDEsIiJdLFsxMiwxNSw2LDEsIiJdLFsxMSwxMSw4LDEsImJyZWFkIl0sWzExLDE2LDgsMSwiYnJlYWQiXSxbMTMsMTUsMCwwLCIlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgbGV0dHVjZSJdLFsxMywxNCwwLDAsIm1lYXQiXSxbMTUsMTMsMCwwLCJjaGVlc2UiXSxbMTMsMTIsMCwwLCJzYXVjZSJdLFsxMiwxMSw2LDAsIiJdLFsxMywxMCwwLDAsInNlc2FtZSBzZWVkcyJdLFsyMSwxLDExLDE3LCIiXSxbMjUsNCwzLDQsIiJdLFsyNCwzLDUsMSwiIl0sWzIzLDgsMSw1LCIiXSxbMjMsMTIsMSwxLCIiXSxbMjQsOCw1LDQsIiJdLFsyOSw4LDEsNSwiIl0sWzI3LDEyLDMsMSwiIl0sWzI3LDEyLDEsMSwiIl0sWzI1LDUsMCwwLCIlQzIlQTAgLyVDMiVBMCBcXCVDMiVBMCAlQzIlQTAgJUMyJUEwLyVDMiVBMCBcXCJdLFsyNiw3LDAsMCwiX19fLyJdLFsyNSwzLDMsMCwiIl0sWzIyLDE1LDAsMCwiJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgTSBvIG4gYSVDMiVBMCAlQzIlQTAgQiBMIFQiXSxbMzMsNSwwLDAsImp1c3Qgc2F3IHRoYXQgc2hlIGhhcyBubyBoYXQiXSxbMzQsOCwwLDAsIm15IGJhZCJdLFsxNCw0LDUsMCwiJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTBcXFxcJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwICVDMiVBMCAlQzIlQTAgJUMyJUEwLy8iXSxbMjYsMjAsMCwwLCJwdXNoIGl0IHRvIHRoZSBsaW1pdHMlQzIlQTAlRTIlOTklQUEiXSxbMzEsMjAsMCwwLCIlRjAlOUYlOEUlQjkiXSxbMzIsMjAsMCwwLCJ3aXRoIGVtb2ppcyBcXG8vIl0sWzAsMTksMCwwLCJhenp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6enp6emVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlcnJycnJycnJycnJycnJycnJycnJycnJycnR0dHR0dHR0dHR0dHR0dHR0dHR0dHl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eSJdXQ==) again.

**Comment by Shuunen** [comment]
[\o/](https://persistence--box-line-text.netlify.app/#W1s4LDYsMSw4LCIiXSxbOSw2LDEsMiwiIl0sWzEwLDcsMSwzLCIiXSxbMTEsOSwxLDMsIiJdLFsxMiw2LDEsOCwiIl0sWzE0LDgsMSw2LCIiXSxbMTQsNiwxLDEsIiVDMiVBMC4iXSxbMTYsOCwxLDUsIiJdLFsxNyw3LDEsMSwiIl0sWzE4LDYsMSwxLCIiXSxbMTksNiwxLDEsIiJdLFsxNywxMywxLDEsIiJdLFsxOCwxMywxLDEsIiJdLFsxOSwxMywxLDEsIiJdLFsyMSw2LDEsOCwiIl0sWzIyLDEzLDQsMSwiIl0sWzIyLDksMiwxLCIiXSxbMjIsNiw0LDEsIiJdLFs3LDE1LDIyLDAsIiJdLFsyOCw2LDAsMTAsIiJdLFs3LDUsMjMsMCwiIl0sWzI4LDQsMCwyLCIiXSxbNiw1LDEsMCwiIl0sWzcsMywwLDEzLCIiXSxbNiwxNSwxLDAsIiJdLFs1LDUsMSwwLCIiXSxbNSwxNSwxLDAsIiJdLFs3LDE2LDAsMSwiIl0sWzI4LDE2LDAsMSwiIl0sWzI5LDE1LDEsMCwiIl0sWzI4LDMsMCwxLCIiXSxbMjQsNiwwLDAsIiVDMiVBMCJdLFsyMyw2LDAsMCwiIl0sWzMyLDcsMCwwLCIiXV0=)
