### ISSUE TITLE
Text superposition

### ISSUE THREAD

**Issue by NicolasUmiastowski** [jncraton/box-line-text#9]
When I already wrote a text, and then I want to edit it, so I type again something in the box, the text is added above the older text.

Don't know if it could just replace the text that is already on the same line?
see screen shot
![line-bug](https://user-images.githubusercontent.com/9115832/93308392-7da7e680-f802-11ea-925a-ffa05698c82b.png)

**Comment by jncraton** [comment]
Thanks for bringing this to my attention.

The expected behavior is that if you click on existing text (not merely inside an existing box but literally on text in the box) then you will be able to edit the text. If you click anywhere else, you will create a new element. If this isn't what you are seeing in your case, please let me know what steps are causing this issue.

There are several ways that text can end up superimposed as shown above. Here's one example:

1. Create a 2x2 box
2. Type a word on the first line
3. Click on the second line
4. Type a word
5. Click on you word on the first line
6. Begin typing more words. These will wrap and become superimposed on the word you already typed in the second line.

Here's an even simpler example:

1. Click somewhere and type
2. Click to the left of your existing text and type
3. You second text item will be superimposed on the first where they overlap

This doesn't look good, but it is also avoidable. My goal with this app was to provide a fairly free-form canvas for boxes, lines, and text. This free-form nature makes the UI simple, but it also means you can create something ugly.

The current implementation makes it simple to create designs with elements placed on top of one another, such as quick UI mockups:

![image](https://user-images.githubusercontent.com/103612/93336805-3fa4c580-f7f6-11ea-951f-1b5ad13d2ba6.png)

I'm certainly open to ideas on how this can be improved, but from my POV what you are seeing currently is expected behavior, and not a bug. I'm hesitant to make stylistic changes here, as it is entirely possible that some folks are using this behavior in creative ways. For example, one could [simulate underlined text](https://box-line-text.netlify.app/#;011Underline;001%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0+________) using this property. I like to be sure I'm not breaking anyone's work.

**Comment by NicolasUmiastowski** [comment]
yes you are right. 
It's not a bug.
Best to keep it like that.
